import * as Schema from "effect/Schema"
import * as SchemaRepresentation from "effect/SchemaRepresentation"

import { UpdateUserAccountInput, UserAccount } from "../../modules/identity/mod.ts"
import {
  ApiConflict,
  ApiForbidden,
  ApiNotFound,
  ApiServiceUnavailable,
  ApiUnauthorized,
  RitseiApi,
} from "../../runtime/api/api.ts"

export function source(): string {
  const schemas = {
    UserAccount,
    UpdateUserAccountInput,
    ApiError: Schema.Union([
      ApiUnauthorized,
      ApiForbidden,
      ApiNotFound,
      ApiConflict,
      ApiServiceUnavailable,
    ]),
  }
  const declarations = Object.entries(schemas).map(([name, schema]) => {
    const representation = SchemaRepresentation.toRepresentation(schema.ast, {
      referencePolicy: () => undefined,
    })
    const document = SchemaRepresentation.toCodeDocument(
      SchemaRepresentation.toMultiDocument(representation),
    )
    if (
      document.artifacts.length > 0 ||
      document.references.nonRecursives.length > 0 ||
      Object.keys(document.references.recursives).length > 0 ||
      Object.keys(representation.references).length > 0 ||
      document.codes.length !== 1
    ) {
      throw new Error(`Unsupported browser contract artifacts or references: ${name}`)
    }
    return `export const ${name} = ${document.codes[0]!.runtime}\n` +
      `export type ${name} = Schema.Schema.Type<typeof ${name}>`
  })
  const endpoints = RitseiApi.groups.UserAccounts.endpoints
  return [
    "// Generated by tooling/frontend/contracts.ts. Do not edit.",
    'import * as Schema from "effect/Schema"',
    ...declarations,
    `export const userAccountRoutes = ${
      JSON.stringify({
        list: endpoints.list.path,
        update: endpoints.update.path,
      })
    } as const`,
    "",
  ].join("\n\n")
}

if (import.meta.main) {
  const output = new URL(
    "../../apps/web/src/shared/contracts/generated/identity.ts",
    import.meta.url,
  )
  await Deno.mkdir(new URL(".", output), { recursive: true })
  await Deno.writeTextFile(output, source())
}
