export const AccountingCapabilities = {
  legalEntityConfigure: "accounting.legal_entity.configure",
  financialEngineActivate: "accounting.financial_engine.activate",
  financialProjectionRebuild: "accounting.financial_projection.rebuild",
  financialEvidenceRecord: "accounting.financial_evidence.record",
  financialEvidenceRead: "accounting.financial_evidence.read",
  financialReconciliationCheckpoint: "accounting.financial_reconciliation.checkpoint",
  accountCreate: "accounting.account.create",
  journalPost: "accounting.journal.post",
  revenueConfigure: "accounting.revenue.configure",
  periodOpen: "accounting.period.open",
  periodClose: "accounting.period.close",
  revenuePost: "accounting.revenue.post",
  revenueReverse: "accounting.revenue.reverse",
} as const
