export const iconRegistry = {
  "action.add": "plus",
  "action.edit": "pencil-simple",
  "action.delete": "trash",
  "action.save": "floppy-disk",
  "action.copy": "copy",
  "action.archive": "archive",
  "action.download": "download-simple",
  "action.upload": "upload-simple",
  "action.refresh": "arrows-clockwise",
  "action.print": "printer",
  "action.search": "magnifying-glass",
  "action.filter": "funnel",
  "action.export": "export",
  "action.import": "file-arrow-up",
  "action.close": "x",
  "action.overflow": "dots-three",
  "action.clear": "x-circle",
  "action.calendar": "calendar",
  "action.reveal": "eye",
  "action.hide": "eye-slash",

  "navigation.home": "house",
  "navigation.sales": "receipt",
  "navigation.procurement": "clipboard-text",
  "navigation.inventory": "package",
  "navigation.manufacturing": "factory",
  "navigation.accounting": "books",
  "navigation.crm": "users-three",
  "navigation.process": "flow-arrow",
  "navigation.settings": "gear",

  "object.customer": "user",
  "object.vendor": "storefront",
  "object.invoice": "invoice",
  "object.payment": "credit-card",
  "object.sales-order": "note",
  "object.purchase-order": "clipboard-text",
  "object.product": "cube",
  "object.inventory": "package",
  "object.warehouse": "warehouse",
  "object.account": "bank",
  "object.journal": "book-open",
  "object.work-order": "clipboard",
  "object.manufacturing-order": "factory",
  "object.transfer": "arrows-left-right",
  "object.process": "flow-arrow",

  "status.success": "check-circle",
  "status.warning": "warning",
  "status.error": "x-circle",
  "status.info": "info",
  "status.pending": "clock",
  "status.processing": "spinner",
  "status.locked": "lock",
  "status.archived": "archive",

  "direction.back": "arrow-left",
  "direction.forward": "arrow-right",
  "direction.up": "arrow-up",
  "direction.down": "arrow-down",

  "disclosure.expand": "caret-right",
  "disclosure.collapse": "caret-down",

  "data.sort-ascending": "sort-ascending",
  "data.sort-descending": "sort-descending",

  "communication.email": "envelope",
  "communication.comment": "chat-circle",

  "security.protected": "shield-check",
  "security.locked": "lock-key",

  "system.help": "question",
  "system.settings": "gear",

  "editor.text": "text-t",
  "editor.list": "list-bullets",

  "ritsei.process": "flow-arrow",
  "ritsei.commitment": "handshake",
  "ritsei.reconciliation": "arrows-counter-clockwise",
  "ritsei.posting": "stamp",
  "ritsei.reservation": "lock-key",

  "empty.purchase-order": "clipboard-text",
  "empty.invoice": "invoice",
} as const

export type IconName = keyof typeof iconRegistry
