import { collectSourceFiles } from "../source-files.ts"

const ownershipFile = "db/ownership.toml"

const parseOwnership = (content: string) => {
  const schemas = new Map<string, string>()
  let inSchemas = false

  for (const [index, rawLine] of content.split("\n").entries()) {
    const line = rawLine.trim()
    if (line === "[schemas]") {
      inSchemas = true
      continue
    }
    if (line.startsWith("[") && line !== "[schemas]") inSchemas = false
    if (!inSchemas || line === "" || line.startsWith("#")) continue

    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*"([^"]+)"$/)
    if (!match) throw new Error(`${ownershipFile}:${index + 1}: invalid schema ownership entry`)

    const [, schema, owner] = match
    if (schemas.has(schema)) throw new Error(`duplicate schema owner: ${schema}`)
    schemas.set(schema, owner)
  }

  if (schemas.size === 0) throw new Error(`${ownershipFile}: no schemas registered`)
  return schemas
}

export const checkOwnership = async (): Promise<readonly string[]> => {
  const schemas = parseOwnership(await Deno.readTextFile(ownershipFile))
  const failures: string[] = []
  const owners = new Set<string>()

  for (const [schema, owner] of schemas) {
    if (owners.has(owner)) failures.push(`multiple schemas use owner ${owner}`)
    owners.add(owner)

    try {
      const info = await Deno.stat(owner)
      if (!info.isDirectory) failures.push(`${schema}: owner is not a directory: ${owner}`)
      await Deno.stat(`${owner}/mod.ts`)
    } catch {
      failures.push(`${schema}: owner must contain a public mod.ts: ${owner}`)
    }
  }

  async function checkMigrations(directory: string): Promise<void> {
    for await (const entry of Deno.readDir(directory)) {
      const path = `${directory}/${entry.name}`
      if (entry.isDirectory) {
        await checkMigrations(path)
        continue
      }
      if (!entry.isFile || !entry.name.endsWith(".sql")) continue

      const sql = await Deno.readTextFile(path)
      const owner = sql.match(/^\s*--\s*owner:\s*([A-Za-z_][A-Za-z0-9_]*)\s*$/m)?.[1]
      const owners = sql.match(/^\s*--\s*owners:\s*(.+)\s*$/m)?.[1]
        ?.split(",")
        .map((value) => value.trim())
        .filter(Boolean) ?? []
      const declaredOwners = owner === undefined ? owners : [owner]

      if (declaredOwners.length === 0) {
        failures.push(
          `${path}: SQL migrations require -- owner: <schema> or -- owners: <schema, ...>`,
        )
      }
      for (const declaredOwner of declaredOwners) {
        if (!schemas.has(declaredOwner)) {
          failures.push(`${path}: unknown schema owner ${declaredOwner}`)
        }
      }
      if (!/^\s*--\s*reviewed:\s*\d{4}-\d{2}-\d{2}\s*$/m.test(sql)) {
        failures.push(`${path}: SQL migrations require a -- reviewed: YYYY-MM-DD header`)
      }
      if (!/^\s*--\s*generated-by:\s*drizzle-kit\s+/m.test(sql)) {
        failures.push(`${path}: migrations must be generated by the pinned Drizzle Kit flow`)
      }
      try {
        const snapshot = await Deno.stat(`${path.slice(0, -"migration.sql".length)}snapshot.json`)
        if (!snapshot.isFile) failures.push(`${path}: Drizzle snapshot.json must be a file`)
      } catch {
        failures.push(`${path}: missing Drizzle snapshot.json`)
      }
    }
  }

  await checkMigrations("db/migrations")

  const sourceOwner = (path: string): string | undefined => {
    const packageName = path.match(/^packages\/([^/]+)\/src\//)?.[1]
    return packageName === undefined ? undefined : `packages/${packageName}`
  }

  const isKernelSchemaTest = (path: string) => path.startsWith("packages/kernel/tests/")

  for (const root of ["apps", "packages", "tests", "tooling"] as const) {
    for (const { path, source } of await collectSourceFiles(root, [".ts"])) {
      for (const match of source.matchAll(/db\/schema\/([A-Za-z_][A-Za-z0-9_-]*)\.ts/g)) {
        const importedSchema = match[1]!
        const importedOwner = schemas.get(importedSchema)
        if (importedOwner === undefined || isKernelSchemaTest(path)) continue
        const owner = sourceOwner(path)
        if (owner === undefined) {
          failures.push(
            `${path}: application, test, and tooling code must use public contracts instead of ${importedSchema} tables`,
          )
        } else if (importedOwner !== owner) {
          failures.push(
            `${path}: ${owner} must not import ${importedSchema} tables owned by ${importedOwner}`,
          )
        }
      }
    }
  }

  return failures
}

if (import.meta.main) {
  const failures = await checkOwnership()
  if (failures.length > 0) {
    console.error(failures.join("\n"))
    Deno.exit(1)
  }
  console.log("schema ownership valid")
}
