/** Compatibility facade for the Accounting public contract. */
export {
  Account,
  AccountingConfiguration,
  AccountingPeriod,
  AccountingService,
  ActivateTigerBeetleCutoverInput,
  ApproveTigerBeetleCutoverInput,
  ClosePeriodInput,
  ConfigureLegalEntityInput,
  ConfigureRevenuePostingInput,
  CreateAccountInput,
  FinancialCutoverControl,
  FinancialVerificationArtifact,
  JournalEntry,
  JournalLine,
  OpenPeriodInput,
  PostJournalInput,
  PostRevenueForOrderInput,
  PrepareTigerBeetleCutoverInput,
  RecordFinancialVerificationArtifactInput,
  RevenuePostingProfile,
  ReverseRevenueForOrderInput,
} from "./service.ts"
export type {
  Account as AccountType,
  AccountingConfiguration as AccountingConfigurationType,
  AccountingPeriod as AccountingPeriodType,
  AccountingService as AccountingServiceShape,
  FinancialVerificationArtifact as FinancialVerificationArtifactType,
  JournalEntry as JournalEntryType,
  JournalLine as JournalLineType,
  RevenuePostingProfile as RevenuePostingProfileType,
} from "./service.ts"

export {
  CreateFinancialJournalIntentInput,
  CreateFinancialRevenueIntentInput,
  CreateFinancialReversalIntentInput,
  FinancialOperation,
  FinancialOperationCommandInput,
  FinancialOperationFailpointName,
  FinancialOperationFailpointService,
  FinancialOperationJobPayload,
  FinancialOperationJournalLine,
  FinancialOperationService,
  FinancialOperationStatus,
  FinancialProjectionRebuildResult,
  FinancialReconciliationCheckpoint,
  RebuildFinancialProjectionInput,
  ReconcileFinancialCheckpointInput,
} from "./financial-operations.ts"
export type {
  CreateFinancialJournalIntentInput as CreateFinancialJournalIntentInputType,
  CreateFinancialRevenueIntentInput as CreateFinancialRevenueIntentInputType,
  CreateFinancialReversalIntentInput as CreateFinancialReversalIntentInputType,
  FinancialOperation as FinancialOperationType,
  FinancialOperationCommandInput as FinancialOperationCommandInputType,
  FinancialOperationFailpointName as FinancialOperationFailpointNameType,
  FinancialOperationFailpointService as FinancialOperationFailpointServiceShape,
  FinancialOperationJobPayload as FinancialOperationJobPayloadType,
  FinancialOperationService as FinancialOperationServiceShape,
  FinancialReconciliationCheckpoint as FinancialReconciliationCheckpointType,
  ReconcileFinancialCheckpointInput as ReconcileFinancialCheckpointInputType,
} from "./financial-operations.ts"

export {
  CreateExecutionAccountInput,
  FinancialAccountConstraint,
  FinancialBalanceOutcome,
  FinancialExecutionOutcome,
  FinancialJournalLine,
  FinancialLedgerAuthority,
  FinancialLedgerPort,
  GetFinancialBalanceInput,
  PostFinancialJournalInput,
} from "./financial-ledger.ts"
