/** Compatibility facade for Accounting's stable tagged failures. */
export {
  AccountAlreadyExists,
  AccountingConfigurationAlreadyExists,
  AccountingLegalEntityNotFound,
  AccountingPeriodNotFound,
  AccountingPeriodNotOpen,
  AccountingPeriodOverlap,
  AccountNotFound,
  FinancialEngineActivated,
  FinancialEngineCutoverBlocked,
  FinancialOperationsPending,
  FinancialVerificationArtifactInvalid,
  FinancialVerificationArtifactNotFound,
  InvalidJournalLine,
  InvalidRevenuePostingProfile,
  JournalIdempotencyConflict,
  JournalReferenceAlreadyExists,
  RevenueJournalNotFound,
  RevenuePostingProfileAlreadyExists,
  RevenuePostingProfileNotFound,
  UnbalancedJournal,
} from "./service.ts"

export {
  FinancialCurrencyMismatch,
  FinancialLedgerNotActivated,
  FinancialLedgerNotConfigured,
  FinancialOperationConflict,
  FinancialOperationInjectedFailure,
  FinancialOperationNotFound,
  FinancialOperationReconciliationConflict,
  FinancialProjectionRebuildBlocked,
  FinancialReconciliationCheckpointConflict,
  FinancialReconciliationCheckpointEvidenceInvalid,
  FinancialRevenueAmountMismatch,
  FinancialReversalAlreadyExists,
  FinancialReversalSourceNotFound,
  FinancialReversalSourceNotPosted,
  FinancialReversalSourceNotReady,
  FinancialReversalSourceRequired,
  FinancialSalesNotConfigured,
} from "./financial-operations.ts"
